In [1]:
import numpy as np

a = np.random.randn(5)
print (a)

[ 1.35625486  1.42561617  1.29403809  0.64370339  0.42092232]


In [2]:
print (a.shape)

(5,)


In [3]:
print (a.T)

[ 1.35625486  1.42561617  1.29403809  0.64370339  0.42092232]


In [4]:
print (np.dot(a,a.T))

6.13787293765


In [6]:
a = np.random.randn(5,1)
print (a)
print (a.T)
print (a.shape)
print (a.T.shape)

[[ 0.76288939]
 [-0.43853185]
 [ 0.06702374]
 [-0.48531974]
 [-0.60743394]]
[[ 0.76288939 -0.43853185  0.06702374 -0.48531974 -0.60743394]]
(5, 1)
(1, 5)


In [7]:
print (np.dot(a,a.T))

[[ 0.58200023 -0.3345513   0.0511317  -0.37024528 -0.46340491]
 [-0.3345513   0.19231018 -0.02939205  0.21282816  0.26637913]
 [ 0.0511317  -0.02939205  0.00449218 -0.03252794 -0.0407125 ]
 [-0.37024528  0.21282816 -0.03252794  0.23553525  0.29479968]
 [-0.46340491  0.26637913 -0.0407125   0.29479968  0.36897599]]


多用下面的(5,1)or(1,5)，少用(5,)这样类型的~~~