In [2]:
import numpy as np

# A表示4种食物的3中营养成分
A = np.array([[56.0,  0.0,    4.4,   68.0],
              [1.2,   104.0,  52.0,  8.0],
              [1.8,   135.0,  99.0,  0.9]])
print (A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [4]:
# 求和，每一种食物(在列上)的总营养成分
cal = A.sum(axis=0)
print (cal)

[  59.   239.   155.4   76.9]


In [5]:
# 求每一种食物的营养成分的占比
percentage = 100 * A / cal.reshape(1,4)
print (percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [11]:
np.array([[1],[2],[3],[4]]) + 100

array([[101],
       [102],
       [103],
       [104]])

In [12]:
np.array([[1, 2, 3],
          [4, 5, 6]]) + np.array([100,200,300])

array([[101, 202, 303],
       [104, 205, 306]])

In [13]:
np.array([[1, 2, 3],
          [4, 5, 6]]) + np.array([[100],[200]])

array([[101, 102, 103],
       [204, 205, 206]])